# Database Configuration
DATABASE_URI = None
DATABASE_NAME = None

# Bot Configuration
BOT_TOKEN = ODU5Njc0NTI4OTQ1NTM3MDY3.YNwISw.1RSA8-hZYJXR3WR_1vX5dG4wBcg
REDIS_CONF = {}

# DBL
DBL_TOKEN = None
DBL_SECRET = None

# Webhooks
STRIPE_KEY = None
STRIPE_WEBHOOK_SECRET = None
GITHUB_WEBHOOK_SECRET = None
